name: XNXX RSS Generator

on:
  schedule:
    - cron: '0 */6 * * *'  # 每1小时运行一次
  workflow_dispatch:       # 支持手动触发

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run RSS generator
        run: |
          python scripts/generate_rss.py

      - name: Commit and push RSS feed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add feed.xml
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
          git push
